name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Create public
      run: |
        mkdir dist
        mkdir dist/version
        mkdir dist/root
        cp index.js dist/version/index.js
        cp metadata.json dist/root/metadata.json

    - id: npmjsVersion
      name: Extract version from package.json
      run: |
        echo "npmjsVersion=`awk '/version/{gsub(/("|",)/,"",$2);print $2};' metadata.json`" >> $GITHUB_OUTPUT

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/root

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/version
        target-folder: v${{ steps.npmjsVersion.outputs.npmjsVersion }}
        clean: true
